### PR TITLE
Switchfunction none

### PR DESCRIPTION
**Pull request by jandom**
A new switch function 'none' that allows user to provide a list of reference distance between contacts, with no switching function to be used. It's similar to intermolecular DRMSD but allows a specific list of contacts to be defined (rather than generated internally by providing the PDB and lower/upper cutoffs)

### CODE REVIEW

**Comment by GiovanniBussi** [comment]
@jandom 
Notice that you open the request on my public clone (GiovanniBussi/plumed2) instead of on the official version (plumed/plumed2). Is that on purpose?

Also, I am not sure it is a good idea to include a switching function that does not go from 1 to 0.

**Comment by jandom** [comment]
Hey Giovanni, 

yeah it probably doesn't belong here but on the plumed2 repository. 

but i would like to argue that it's a useful feature: while maybe a misnomer, it allows the user to pass a list of reference distances and bias along those with no switching function that may be useful in some cases: where inter-molecular DRMSD via a structure separated by TERs is not appropriate, for example.

Now, perhaps calling it a switchfunction "none" is bad but the feature was certainly useful to me

**Comment by jandom** [comment]
@GiovanniBussi is there any chance we can revisit this? I'm pretty sure some folks would like to (like me) use an arbitrary distance list without any switching function (DRMSD-style but with no ref structure, just ref distances). Should i re-submit this to the plumed2/plumed2 repository instead?

**Comment by GiovanniBussi** [comment]
You should open it on the main repository so that we discuss it there

Giovanni

**Pull request closed without merging**
